### ISSUE TITLE
Please add authorization example

### ISSUE THREAD

**Issue by hilfor** [sugoiJS/demo#1]
**Is your feature request related to a problem? Please describe.**
I'd like to get authorization data (userId, token etc.) inside the controller. Can you please add an example of that in the demo please.

**Comment by o-b-one** [comment]
Hi @hilfor,

Authorization were added as part of `@sugoi/server` version 2.2.1, 

An example already exists on the demo project under:

- server/src/core/classes/authorization.class.ts
- server/src/modules/index/controllers/index.controller.ts -> changeColor()

Further information will add to the documentation on the next couple of days.

Cheers!
